exe:	client.cpp
	g++ client.cpp -g -O2 src/*.cpp src/*.c `sdl-config --cflags --libs` -lSDL_image -lSDL_mixer -lSDL_ttf -lSDL_net -Iincludes -o main

run:
	./a.out

r:
	./a.out

clean:
	rm a.out

c:
	rm a.out

pull:
	git pull

push:
	git push https://github.com/dgforck1/Chess-

commit:
	git commit -a

add:
	git add -A
